### ISSUE TITLE
error to activate 2FA

### ISSUE THREAD

**Issue by brunoaumaxs** [sysPass/plugin-Authenticator#33]
I installed the Plugin and enabled it in my environment, but I was unable to activate this function in users. 
Does anyone know how to activate?

![image](https://user-images.githubusercontent.com/60828751/110833692-7c201e00-827b-11eb-9df4-f9021b421f84.png)

**Comment by nuxsmin** [comment]
Hello,

after the plugin activation, every user need to pair the code generator in their preference settings.

Regards

**Comment by brunoaumaxs** [comment]
I was able to activate the plugin but it does not generate QRCODE.

![image](https://user-images.githubusercontent.com/60828751/111176829-6f0b7380-8588-11eb-845a-7ed089707604.png)

**Comment by xenofree** [comment]
Same problem here with syspass v3.2.2
The qrcode doesn't appear.

**Comment by LuigiPolidorio** [comment]
Same problem here.

**Comment by nuxsmin** [comment]
Hello,

this issue was solved in latest plugin's version.

Regards

**Comment by luizgustavotorres** [comment]
Hello, 

 Same problem here.

![NAO_FAZ_SENTIDO](https://user-images.githubusercontent.com/87499491/125851888-16fb2148-3eff-4c9e-aa54-bef9e436f234.png)

<img width="929" alt="NAO_EH_FACIL" src="https://user-images.githubusercontent.com/87499491/125852118-2c3eeebc-7bed-4dd0-b058-a746c48a14f3.png">

@nuxsmin which version was the fix applied?

**Comment by LuigiPolidorio** [comment]
It's not fixed yet at version 2.2. I have the same problem yet.

**Comment by LuigiPolidorio** [comment]
I saw on the code that it's calling the function `getUserQRFromServer()`, and it get a error because of the BaconQrCode lib. 
But I saw there is a function called `getQrCodeFromUrl()`, and it's not called anywhere, why it`s not used? I think it can solve the problem.

**Comment by LuigiPolidorio** [comment]
I have the fix here. Could you please give me write permission on the repository?
